### ISSUE TITLE
Error while importing

### ISSUE THREAD

**Issue by AruljothySundaramoorthy** [sindresorhus/is-image#15]
Error [ERR_REQUIRE_ESM]: require() of ES Module not supported.
Instead change the require of index.js in  validator.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> ( validator.js:1:21) {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
