### ISSUE TITLE
Error when compiling with webpack -p.

### ISSUE THREAD

**Issue by mjoynes-wombat-web** [sindresorhus/is-image#4]
This causes an error when it's included in a project and you are bundling with webpack -p.

This is the error.
ERROR in bundle.js from UglifyJs
Unexpected token: operator (>) [bundle.js:75024,27]

**Comment by SamVerschueren** [comment]
We aim for Node.js, not the browser. Uglify can't handle ES2015 characters. You can find a more detailed explanation here https://github.com/sindresorhus/ama/issues/446.

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
