### ISSUE TITLE
Webpack -p Build Error

### ISSUE THREAD

**Issue by mjoynes-wombat-web** [sindresorhus/is-image#5]
This causes an error when it's included in a project and you are bundling with webpack -p.

This is the error.
ERROR in bundle.js from UglifyJs
Unexpected token: operator (>) [bundle.js:75024,27]

I'm using all sorts of ES2015 in my code without issue.
The webpack config I'm running is using babel to transpile with these presets:
presets: ['env', 'stage-0', 'react', 'es2015']

**Comment by sindresorhus** [comment]
This is not the place to ask for Webpack support.

https://github.com/sindresorhus/is-image/issues/4

**Comment by kellyrmilligan** [comment]
https://www.npmjs.com/package/is-image-filename

I published a version thats compatible with webpack. for some of us using create react app, having a new babel plugin is not an option ATM.
