### ISSUE TITLE
Needs more test cases

### ISSUE THREAD

**Issue by Lwdthe1** [sindresorhus/is-image#7]
Thanks for this module. I just noticed some failed tests

The url `example.png` is not an image, but is-image says it is an image

The url `example.png?size=1&color=b` is  an image, but is-image says that it is not an image, and I think its because of the query string

**Comment by sindresorhus** [comment]
From the top of the readme:

> It just checks the extension. Use image-type if you want to check the actual file.

**Comment by Lwdthe1** [comment]
Ah, thanks for pointing that out.
