### ISSUE TITLE
Handle filename with dots

### ISSUE THREAD

**Issue by KnupMan** [sindresorhus/is-image#8]
Just found the case, when I have a file with a dots before the actual extention.
Example:
```
const isImage = require('is-image');
isImage('file.with.dots.mp3'); // => false
```
@sindresorhus what if such case will be handled by `is-image` lib?

**Comment by sindresorhus** [comment]
`is-image` only considers the part after the last dot, so that should already be handled. Your example is invalid as you have left out the image extension.

**Comment by KnupMan** [comment]
Sorry, my fault, `is-image` is working perfectly with files with dot in the name, it's only about `is-audio` package, so it's not a place for the discussion here.
