### ISSUE TITLE
Uses `path` module which is no longer polyfilled in webpack 5

### ISSUE THREAD

**Issue by wmertens** [sindresorhus/is-image#9]
when using this module in the browser, webpack 5 complains about no longer polyfilling `path`.

Perhaps you can depend on path-browserify? Or use just [its extname](https://github.com/browserify/path-browserify/blob/e4e0cd1d848bc4e32ae7e234e560d2f0f146585e/index.js#L389-L436) function?

**Comment by sindresorhus** [comment]
Webpack 5 is not out yet. If they really go that way in the final v5 release, it's up to them to deal with the outcome. I'm not interested in polyfilling Node.js APIs in my modules. You should instead complain on the Webpack issue tracker.
